FROM python:3
ENV PYTHONUNBUFFERED 1
ENV SECRET_KEY abdcsa
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/

CMD python weather_station/manage.py runserver 0.0.0.0:8000